# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-12 21:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PyStudent', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='alumno',
            managers=[
            ],
        ),
    ]
