# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-20 01:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PyStudent', '0002_auto_20170412_1656'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='alumno',
            name='apellidos',
            field=models.CharField(default='N/A', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alumno',
            name='fechaNac',
            field=models.CharField(default='19704/2017', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alumno',
            name='password',
            field=models.CharField(default=1234, max_length=20),
            preserve_default=False,
        ),
    ]
