# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-20 16:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PyStudent', '0003_auto_20170419_2005'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='estado',
            field=models.CharField(default='algo', max_length=100),
            preserve_default=False,
        ),
    ]
