# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-20 19:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PyStudent', '0004_alumno_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Palabras',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('palabra', models.CharField(max_length=100)),
            ],
        ),
    ]
