# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-20 21:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PyStudent', '0005_palabras'),
    ]

    operations = [
        migrations.CreateModel(
            name='Puntaje',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idUsuario', models.CharField(max_length=3)),
                ('aciertos', models.CharField(max_length=3)),
                ('errores', models.CharField(max_length=3)),
            ],
        ),
    ]
