# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-01 16:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PyStudent', '0006_puntaje'),
    ]

    operations = [
        migrations.AddField(
            model_name='palabras',
            name='dificultad',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
