# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-11 12:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PyStudent', '0009_auto_20170511_0713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puntaje',
            name='idUsuario',
            field=models.IntegerField(),
        ),
    ]
