# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-11 12:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PyStudent', '0010_auto_20170511_0714'),
    ]

    operations = [
        migrations.AddField(
            model_name='puntaje',
            name='fecha',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
