# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-12 15:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('PyStudent', '0011_puntaje_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='puntaje',
            name='tiempo',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='puntaje',
            name='fecha',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
