# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-12 15:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PyStudent', '0012_auto_20170512_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puntaje',
            name='tiempo',
            field=models.CharField(default='00:00', max_length=10),
        ),
    ]
